### ISSUE TITLE
List ne passe pas la validation avec le query actuel du frontend

### ISSUE THREAD

**Issue by mamarmite** [Avantage-Numerique/bdsol-api#23]
### Étapes :
Démarrer l'API et l'app en dev. 
Se rendre sur la page d'accueil.
Observer l'erreur du get

### Trace : (pour Personnes et pour Organisation)
```
Erreurs : isDefined : n'est pas définie (typeof == undefined || == null).idValid : L'id fournit n'est pas valide (.length != 24).
```

**Comment by SonofaPancak** [comment]
Une erreur de copy paste, les routes appellaient la fonction update sur le /list et /search. Donc les règles de validation et de retour n'était pas bon.
