### ISSUE TITLE
Sanitization causes problem when creating org with url

### ISSUE THREAD

**Issue by SonofaPancak** [Avantage-Numerique/bdsol-api#34]
Lors de la création d'une organisation dans postman, (je pense que c'est le sanitizer) retire le https ainsi que l'adresse url envoyée, résultant en une adresse invalide.

localhost:8000/organisation/create :

```
    v_data.name = "Librairie Pommerleau";
    v_data.description = "Librairie de petits marchandeurs";
    v_data.url = "https://lalibrairiepommerleau.meilleur";
    v_data.contactPoint = "info@meilleurelibrairie.meilleurfois2"
    v_data.dateDeFondation = "asdf"
```
Le url se réduit à  :    "url": "://."

**Comment by mamarmite** [comment]
Je vais avoir besoin de ton aide pour la regex de l'url @SonofaPancak

**Comment by SonofaPancak** [comment]
J'ai rien tester
Voici ma solution (de ma tête) :
/((http)?s?(:\/\/)?)?(www.)?[a-zA-Z0-9\/]+\.[a-zA-Z]+[\/a-zA-Z0-9=%?.]*/
La regex semble fonctionner, mais je sais pas si sa passe sur le javascript (J'ai mis ma regex entre "/ regex /")

Voici un site que j'ai trouver une regex "javascript" pour url
https://urlregex.com/

/((([A-Za-z]{3,9}:(?:\/\/)?)(?:[\-;:&=\+\$,\w]+@)?[A-Za-z0-9\.\-]+|(?:www\.|[\-;:&=\+\$,\w]+@)[A-Za-z0-9\.\-]+)((?:\/[\+~%\/\.\w\-_]*)?\??(?:[\-\+=&;%@\.\w_]*)#?(?:[\.\!\/\\\w]*))?)/

Celle-ci semble plus permitive!

**Comment by SonofaPancak** [comment]
L'envoi d'un string vide retourne "url":"about:blank"
ahahah
Si ça peut aider à trouver le problème :P

**Comment by SonofaPancak** [comment]
N'importe quel org create, sans url, est problématique*

**Comment by mamarmite** [comment]
@SonofaPancak c'est un replace que je fais avant de sanitizer l'url. J'ai l'impression qu'il faut adapté le regex pour ça

**Comment by mamarmite** [comment]
Ok j'ai ajusté e checkup avant la sanatization. Le about:blank peut encore subvenir, mais ça serait seulement si l'url contient des trucs flaggé comme vraiment pas une url.

On réouvre si j'ai manquer un cas ou si on trouve le même comportement. Mais les tests passe aujourd'hui.
