### ISSUE TITLE
[Dev] UserHistory validation failed 

### ISSUE THREAD

**Issue by mamarmite** [Avantage-Numerique/bdsol-api#42]
**Décrivez le bogue**
Lors d'ajout dans la bd via les formulaires, les userHistory failed lors de la validation.
`message: UserHistory validation failed: user: Path `user` is required.`

**Qu'elles sont les étapes à suivre pour reproduire le bogue ?**
Étapes pour le reproduire
1. Se rendre dans contribuer / organisation, ensuite tester le super repeater et saved.
2. Est-ce que vous êtes connecté ? Oui
3. Save du formulaire
4. Lors de la création du userHistory

**Qu'est-ce qu'on aurait dû observer**
Aucune erreur et un log de mongo qui dit qu'il a créer un userHistory

**Vous avez observé ce problème sur quelle(s) plateforme(s) ?**
- Windows 10 (dans la console).

**Sur votre Téléphone / Tablette ?**
 - PC

**Est-ce que vous auriez une hypothèse pour régler le problème / début d'implémentation ?**
Peut-être dû au DTO qui change l'endroit du user pour le userHistory

**Comment by SonofaPancak** [comment]
ajout d'un underscore " _ " pour fix
